// Pichwai-themed payment receipt email — returns HTML string

interface Params {
  guestName:  string;
  amount:     number;
  bookingRef: string;
  vendorName: string;
  paymentId:  string;
}

export function buildPaymentReceiptHtml(p: Params): string {
  const amountStr = `₹${p.amount.toLocaleString('en-IN')}`;
  const appUrl    = process.env.NEXT_PUBLIC_APP_URL ?? 'https://eventnest.in';
  const date      = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>Payment Receipt</title></head>
<body style="margin:0;padding:0;background:#FFF8F0;font-family:sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FFF8F0;">
<tr><td align="center" style="padding:24px 16px;">
<table role="presentation" width="560" cellpadding="0" cellspacing="0"
  style="max-width:560px;width:100%;background:#FFFDF8;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(62,32,0,0.10);">

  <!-- Header -->
  <tr><td style="background:linear-gradient(135deg,#3E2000,#6B3A1F);padding:28px 32px;">
    <h1 style="color:#C9933A;font-size:11px;letter-spacing:4px;text-transform:uppercase;margin:0 0 4px;font-weight:400;">EventNest</h1>
    <p style="color:#F4E4C1;font-size:18px;margin:0;font-weight:600;">Payment Receipt</p>
  </td></tr>

  <!-- Amount hero -->
  <tr><td align="center" style="background:#F9F5E8;padding:28px 32px;border-bottom:2px dashed #C9933A;">
    <p style="color:#8B6914;font-size:12px;letter-spacing:2px;text-transform:uppercase;margin:0 0 4px;">Amount Paid</p>
    <p style="color:#3E2000;font-size:42px;font-weight:700;margin:0;line-height:1.1;">${amountStr}</p>
    <p style="color:#8B6914;font-size:13px;margin:4px 0 0;">${date}</p>
  </td></tr>

  <!-- Details table -->
  <tr><td style="padding:24px 32px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      ${[
        ['Receipt For',     p.guestName],
        ['Booking Ref',    `<strong>${p.bookingRef}</strong>`],
        ['Vendor',          p.vendorName],
        ['Transaction ID', `<code style="background:#F4E4C1;padding:2px 6px;border-radius:4px;font-size:12px;">${p.paymentId}</code>`],
        ['Status',         `<span style="color:#2E7D32;font-weight:600;">✓ Successful</span>`],
      ].map(([label, value]) => `
      <tr>
        <td style="padding:8px 0;border-bottom:1px solid #F4E4C1;color:#8B6914;font-size:13px;width:40%;">${label}</td>
        <td style="padding:8px 0;border-bottom:1px solid #F4E4C1;color:#3E2000;font-size:14px;">${value}</td>
      </tr>`).join('')}
    </table>
  </td></tr>

  <!-- CTA -->
  <tr><td align="center" style="padding:16px 32px 28px;">
    <a href="${appUrl}/host/dashboard"
      style="display:inline-block;padding:12px 36px;background:linear-gradient(135deg,#C9933A,#F4A825);color:#fff;font-weight:bold;text-decoration:none;border-radius:50px;font-size:14px;">
      View Dashboard
    </a>
    <p style="color:#8B6914;font-size:12px;margin:12px 0 0;">Keep this email as your payment confirmation.</p>
  </td></tr>

  <!-- Footer -->
  <tr><td align="center" style="border-top:1px solid #F4E4C1;padding:16px 32px;">
    <p style="color:#8B6914;font-size:11px;margin:0;">
      This receipt was generated by <strong style="color:#C9933A;">EventNest</strong>.<br/>
      Powered by Razorpay — Payments are secure and encrypted.
    </p>
  </td></tr>
  <tr><td style="background:linear-gradient(135deg,#C9933A,#F4A825);height:5px;"/></tr>
</table></td></tr></table>
</body></html>`;
}
